version: '3.5'

services:
  adescomctmbillings:
    image: bartekkois/adescomctmbillings:1.0.5
    restart: always
    volumes:
      - /docker/AdescomCTMBillings/appsettings.json:/app/appsettings.json:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5001:80"
