version: '3.5'

services:
  adescomctmbillings:
    image: bartekkois/adescomctmbillings:1.0.6
    restart: always
    volumes:
      - /docker/AdescomCTMBillings/appsettings.json:/app/appsettings.json:ro
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: ./Dockerfile
